### ISSUE TITLE
How to setup Django + Gunicorn + Uvicron

### ISSUE THREAD

**Issue by sh1man** [tintoy/seqlog#70]
How to set this up for a django project ?

**Comment by tintoy** [comment]
Sorry for the delay; work’s been a little crazy this week 🙂

I’ll do some research and let you know what I find.

**Comment by tintoy** [comment]
This is probably the place to start:

https://docs.djangoproject.com/en/5.1/topics/logging/

I’ll see if I can adapt a section of the Seqlog documentation to show where you’d customise it for Seqlog:

https://seqlog.readthedocs.io/en/latest/usage.html#configure-logging-from-a-file

(mostly, just converting that YAML to JSON should be sufficient)

**Comment by sh1man** [comment]
cofig yaml not support_extra_properties

**Comment by sh1man** [comment]
is not supported by YAML config

logger.info(
   "{cam_direction}, {stream}",
    cam_direction=stream_source.cam_direction,
    stream=stream_source.name,
)

**Comment by tintoy** [comment]
Both `configure_from_yaml` and `configure_from_dict` accept a `support_extra_properties` parameter which enables that support:

https://github.com/tintoy/seqlog/blob/02270aac00e3b6b166b7020741f4a192322b2095/seqlog/__init__.py#L62

**Comment by sh1man** [comment]
![image](https://github.com/user-attachments/assets/7a2bc378-f719-4d0b-a35e-076120e747b9)

**Comment by tintoy** [comment]
Sorry, but I don’t think it supports doing it like that. That flag is respected by the loader methods but has to be specified at load time, not inside the loaded YAML.

**Comment by sh1man** [comment]
i use python-dependency-injector
https://python-dependency-injector.ets-labs.org/api/providers.html#dependency_injector.providers.Configuration.from_yaml

**Comment by sh1man** [comment]
If I specify the line support_extra_properties in the yaml file, it raises an exception

**Comment by tintoy** [comment]
What exception?

**Comment by tintoy** [comment]
I’m guessing it’s because that is the name of one of the loader method parameters? I’ve never used  python-dependency-injector, myself, so I’m not sure of the mechanics there.

**Comment by tintoy** [comment]
It was a while ago, but think reason I built those loader methods was because there was a bunch of out-of-band configuration required which the standard logging configuration mechanism didn’t support (at the time, anyway).

**Comment by tintoy** [comment]
The other way to enable that feature is like so:

https://github.com/tintoy/seqlog/blob/02270aac00e3b6b166b7020741f4a192322b2095/seqlog/__init__.py#L8
then
https://github.com/tintoy/seqlog/blob/02270aac00e3b6b166b7020741f4a192322b2095/seqlog/__init__.py#L70

**Comment by tintoy** [comment]
Ah, I think that relates to the `style` parameter:

https://docs.python.org/3/library/logging.html#logging.basicConfig

(needs to be `{` I think)

**Comment by sh1man** [comment]
Yes, he was listed

![image](https://github.com/user-attachments/assets/e85c5f47-c0d9-4a22-96dd-61978c0ff0f6)

**Comment by sh1man** [comment]
> ![image](https://private-user-images.githubusercontent.com/49469606/392799049-56f8858f-5ed2-464e-9598-a0854284a2e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDA0MDMsIm5iZiI6MTczMzQwMDEwMywicGF0aCI6Ii80OTQ2OTYwNi8zOTI3OTkwNDktNTZmODg1OGYtNWVkMi00NjRlLTk1OTgtYTA4NTQyODRhMmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDEyMDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMDc2ZDgxNzc1OWEzZTFmMzM2MTAyZDM4M2NjZjQ2YmUzYjcyZGRlYTYwNTU1YTk3YjMzZDJlNTNhOWU0MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aLEm3Ci6Avn4V9YsIFZCSPfT7WzjvOsMH1_hrLuujlo)
> 
> ```
> [Traceback (most recent call last):
>   File "D:\data\Project\analytic_barrier\analytic_barrier_core\tests\memcache_test.py", line 20, in <module>
>     logger.info("{name}", name=123)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1477, in info
>     self._log(INFO, msg, args, **kwargs)
> TypeError: Logger._log() got an unexpected keyword argument 'name'](url)
> ```

I'm still getting this error

**Comment by tintoy** [comment]
Hmm, in that case don’t understand what is going on there; `name` definitely isn’t a keyword parameter supported by `Logger._log()` (or `StructuredLogger._log()`).

It might have something to do with this:

https://github.com/tintoy/seqlog/blob/02270aac00e3b6b166b7020741f4a192322b2095/seqlog/structured_logging.py#L196

**Comment by tintoy** [comment]
What happens if you remove the other logger?

**Comment by sh1man** [comment]
![image](https://github.com/user-attachments/assets/8135d40c-a690-42bf-997d-063802fe9003)

![image](https://github.com/user-attachments/assets/1ce7eead-8bfb-4353-b25a-d93d6bc0e65c)
Strange, if you use the log_to_seq setting it works, I don't understand it

**Comment by tintoy** [comment]
I think it’s because regular logging doesn’t really support the logging-from-keyword-arguments trick (hence resetting the logger class to `StructuredLogger`)… are you able to set the logger class from the config YAML?

**Comment by sh1man** [comment]
how to setup StructuredLogger ?

**Comment by tintoy** [comment]
Like this:

https://github.com/tintoy/seqlog/blob/02270aac00e3b6b166b7020741f4a192322b2095/seqlog/__init__.py#L120

**Comment by tintoy** [comment]
(https://docs.python.org/3/library/logging.html#logging.setLoggerClass)

**Comment by sh1man** [comment]
didn't work, I'm also getting an error

Traceback (most recent call last):
  File "D:\data\Project\analytic_barrier\analytic_barrier_core\tests\memcache_test.py", line 18, in <module>
    logger.info("{name}", name=123)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
TypeError: Logger._log() got an unexpected keyword argument 'name'

```
import logging
import time

from dependency_injector import providers
from seqlog import FeatureFlag, configure_feature, StructuredLogger

from src.dependency.stream_containers import StreamApplication

if __name__ == '__main__':
    application = StreamApplication()
    config = providers.Configuration()
    config.from_yaml('app_config_debug.yml')
    application.config.override(config)
    application.core.init_resources()
    logging.setLoggerClass(StructuredLogger)
    logger = logging.getLogger("stream_process_handler")
    configure_feature(FeatureFlag.EXTRA_PROPERTIES, True)
    logger.info("{name}", name=123)
```

**Comment by sh1man** [comment]
I noticed that if you create a separate process, this code will not work in it and the same error will be thrown.

logging.setLoggerClass(StructuredLogger)

```
   logger.info(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
```

**Comment by tintoy** [comment]
I’m not familiar with that instancing model, but I imagine it would need to run that same setup code (setLoggerClass) in any sub-processes before any loggers are initialised.

How are you creating the sub-process?

**Comment by tintoy** [comment]
I wonder if this might be related:

https://github.com/fastapi/fastapi/issues/1508#issuecomment-638365277

**Comment by sh1man** [comment]
Thank you. I'll give it a try.

**Comment by wuchang** [comment]
try this #84
